"""
Pydantic data models for strategy engine.
Defines schemas for signals, positions, orders, backtesting, and ML models.
"""

from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, validator
import numpy as np


class Side(str, Enum):
    """Order/position side."""
    BUY = "BUY"
    SELL = "SELL"
    LONG = "LONG"
    SHORT = "SHORT"


class OrderType(str, Enum):
    """Order type enumeration."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"
    ICEBERG = "ICEBERG"
    TWAP = "TWAP"
    VWAP = "VWAP"


class OrderStatus(str, Enum):
    """Order status enumeration."""
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL = "PARTIAL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class PositionStatus(str, Enum):
    """Position status enumeration."""
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"


class SignalType(str, Enum):
    """Signal type classification."""
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    REBALANCE = "REBALANCE"
    HEDGE = "HEDGE"


class AssetClass(str, Enum):
    """Asset class enumeration."""
    EQUITY = "equity"
    FOREX = "forex"
    CRYPTO = "crypto"
    COMMODITY = "commodity"
    BOND = "bond"
    OPTION = "option"
    FUTURE = "future"


# Base model with common fields
class BaseStrategyModel(BaseModel):
    """Base model for all strategy-related schemas."""
    timestamp: datetime = Field(..., description="Event timestamp in UTC")
    strategy_id: str = Field(..., description="Strategy identifier")
    
    @validator("timestamp", pre=True)
    def parse_timestamp(cls, v):
        """Convert various timestamp formats to datetime."""
        if isinstance(v, (int, float)):
            if v > 1e10:  # Milliseconds
                v = v / 1000
            return datetime.fromtimestamp(v, tz=timezone.utc)
        elif isinstance(v, str):
            return datetime.fromisoformat(v.replace('Z', '+00:00'))
        elif isinstance(v, datetime):
            if v.tzinfo is None:
                return v.replace(tzinfo=timezone.utc)
            return v.astimezone(timezone.utc)
        return v
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat(),
            Decimal: str,
        }
        use_enum_values = True


class Signal(BaseStrategyModel):
    """Trading signal generated by strategy."""
    symbol: str = Field(..., description="Trading symbol")
    signal_type: SignalType = Field(..., description="Type of signal")
    side: Side = Field(..., description="Trade direction")
    strength: float = Field(..., description="Signal strength (0-1)", ge=0, le=1)
    confidence: float = Field(..., description="Signal confidence (0-1)", ge=0, le=1)
    
    # Price and sizing information
    target_price: Optional[Decimal] = Field(None, description="Target entry/exit price")
    stop_price: Optional[Decimal] = Field(None, description="Stop loss price")
    take_profit_price: Optional[Decimal] = Field(None, description="Take profit price")
    position_size: Optional[Decimal] = Field(None, description="Suggested position size")
    
    # Signal metadata
    indicators: Dict[str, float] = Field(default_factory=dict, description="Supporting indicators")
    features: Dict[str, float] = Field(default_factory=dict, description="ML features if applicable")
    reasoning: Optional[str] = Field(None, description="Human-readable reasoning")
    
    # Timing and validity
    valid_until: Optional[datetime] = Field(None, description="Signal expiration time")
    execution_horizon: Optional[int] = Field(None, description="Expected execution time in seconds")
    
    @validator("strength", "confidence")
    def validate_probabilities(cls, v):
        """Ensure probability values are valid."""
        if not 0 <= v <= 1:
            raise ValueError("Probability values must be between 0 and 1")
        return v


class Position(BaseStrategyModel):
    """Trading position representation."""
    position_id: str = Field(..., description="Unique position identifier")
    symbol: str = Field(..., description="Trading symbol")
    side: Side = Field(..., description="Position side")
    quantity: Decimal = Field(..., description="Position quantity")
    
    # Price information
    entry_price: Decimal = Field(..., description="Average entry price")
    current_price: Optional[Decimal] = Field(None, description="Current market price")
    
    # P&L tracking
    unrealized_pnl: Decimal = Field(default=Decimal('0'), description="Unrealized P&L")
    realized_pnl: Decimal = Field(default=Decimal('0'), description="Realized P&L")
    total_pnl: Optional[Decimal] = Field(None, description="Total P&L")
    
    # Cost basis and fees
    cost_basis: Decimal = Field(..., description="Total cost basis")
    commission_paid: Decimal = Field(default=Decimal('0'), description="Total commissions")
    
    # Risk metrics
    var_95: Optional[Decimal] = Field(None, description="Value at Risk 95%")
    beta: Optional[float] = Field(None, description="Beta vs benchmark")
    
    # Position management
    status: PositionStatus = Field(default=PositionStatus.OPEN, description="Position status")
    stop_loss: Optional[Decimal] = Field(None, description="Stop loss price")
    take_profit: Optional[Decimal] = Field(None, description="Take profit price")
    
    # Metadata
    opened_at: datetime = Field(..., description="Position open timestamp")
    closed_at: Optional[datetime] = Field(None, description="Position close timestamp")
    tags: List[str] = Field(default_factory=list, description="Position tags")
    
    @validator("total_pnl", always=True)
    def calculate_total_pnl(cls, v, values):
        """Auto-calculate total P&L if not provided."""
        if v is None:
            unrealized = values.get("unrealized_pnl", Decimal('0'))
            realized = values.get("realized_pnl", Decimal('0'))
            return unrealized + realized
        return v


class Order(BaseStrategyModel):
    """Order representation for execution."""
    order_id: str = Field(..., description="Unique order identifier")
    client_order_id: str = Field(..., description="Client-side order ID")
    symbol: str = Field(..., description="Trading symbol")
    
    # Order details
    order_type: OrderType = Field(..., description="Order type")
    side: Side = Field(..., description="Order side")
    quantity: Decimal = Field(..., description="Order quantity")
    price: Optional[Decimal] = Field(None, description="Order price (for limit orders)")
    stop_price: Optional[Decimal] = Field(None, description="Stop price (for stop orders)")
    
    # Execution details
    filled_quantity: Decimal = Field(default=Decimal('0'), description="Filled quantity")
    avg_fill_price: Optional[Decimal] = Field(None, description="Average fill price")
    status: OrderStatus = Field(default=OrderStatus.PENDING, description="Order status")
    
    # Order management
    time_in_force: str = Field(default="GTC", description="Time in force")
    position_id: Optional[str] = Field(None, description="Associated position ID")
    parent_order_id: Optional[str] = Field(None, description="Parent order ID for brackets")
    
    # Execution tracking
    submitted_at: Optional[datetime] = Field(None, description="Order submission time")
    filled_at: Optional[datetime] = Field(None, description="Order fill time")
    commission: Decimal = Field(default=Decimal('0'), description="Commission paid")
    
    # Risk and validation
    risk_approved: bool = Field(default=False, description="Risk management approval")
    reject_reason: Optional[str] = Field(None, description="Rejection reason if applicable")


class Portfolio(BaseStrategyModel):
    """Portfolio snapshot and metrics."""
    portfolio_id: str = Field(..., description="Portfolio identifier")
    
    # Current state
    total_value: Decimal = Field(..., description="Total portfolio value")
    cash_balance: Decimal = Field(..., description="Available cash")
    invested_value: Decimal = Field(..., description="Value of positions")
    
    # Performance metrics
    total_return: Decimal = Field(..., description="Total return since inception")
    daily_return: Decimal = Field(..., description="Daily return")
    unrealized_pnl: Decimal = Field(..., description="Total unrealized P&L")
    realized_pnl: Decimal = Field(..., description="Total realized P&L")
    
    # Risk metrics
    leverage: float = Field(..., description="Portfolio leverage")
    var_95: Decimal = Field(..., description="Portfolio VaR 95%")
    max_drawdown: Decimal = Field(..., description="Maximum drawdown")
    beta: float = Field(..., description="Beta vs benchmark")
    sharpe_ratio: Optional[float] = Field(None, description="Sharpe ratio")
    
    # Position breakdown
    positions: List[Position] = Field(default_factory=list, description="Current positions")
    position_count: int = Field(..., description="Number of positions")
    
    # Exposure analysis
    long_exposure: Decimal = Field(..., description="Long exposure")
    short_exposure: Decimal = Field(..., description="Short exposure")
    net_exposure: Decimal = Field(..., description="Net exposure")
    gross_exposure: Decimal = Field(..., description="Gross exposure")
    
    # Asset allocation
    allocation_by_asset_class: Dict[str, Decimal] = Field(
        default_factory=dict, 
        description="Allocation by asset class"
    )
    allocation_by_strategy: Dict[str, Decimal] = Field(
        default_factory=dict,
        description="Allocation by strategy"
    )


class BacktestResult(BaseModel):
    """Backtesting results and performance metrics."""
    backtest_id: str = Field(..., description="Unique backtest identifier")
    strategy_name: str = Field(..., description="Strategy name")
    
    # Time period
    start_date: datetime = Field(..., description="Backtest start date")
    end_date: datetime = Field(..., description="Backtest end date")
    duration_days: int = Field(..., description="Backtest duration in days")
    
    # Setup parameters
    initial_capital: Decimal = Field(..., description="Initial capital")
    commission_rate: float = Field(..., description="Commission rate used")
    slippage_model: str = Field(..., description="Slippage model used")
    
    # Performance metrics
    total_return: float = Field(..., description="Total return %")
    annual_return: float = Field(..., description="Annualized return %")
    volatility: float = Field(..., description="Annualized volatility %")
    sharpe_ratio: float = Field(..., description="Sharpe ratio")
    sortino_ratio: float = Field(..., description="Sortino ratio")
    calmar_ratio: float = Field(..., description="Calmar ratio")
    
    # Risk metrics
    max_drawdown: float = Field(..., description="Maximum drawdown %")
    var_95: float = Field(..., description="Value at Risk 95%")
    cvar_95: float = Field(..., description="Conditional VaR 95%")
    beta: float = Field(..., description="Beta vs benchmark")
    
    # Trade statistics
    total_trades: int = Field(..., description="Total number of trades")
    winning_trades: int = Field(..., description="Number of winning trades")
    losing_trades: int = Field(..., description="Number of losing trades")
    win_rate: float = Field(..., description="Win rate %")
    avg_win: float = Field(..., description="Average winning trade %")
    avg_loss: float = Field(..., description="Average losing trade %")
    profit_factor: float = Field(..., description="Profit factor")
    
    # Detailed results
    daily_returns: List[float] = Field(default_factory=list, description="Daily returns")
    equity_curve: List[float] = Field(default_factory=list, description="Equity curve values")
    drawdown_series: List[float] = Field(default_factory=list, description="Drawdown series")
    trade_log: List[Dict] = Field(default_factory=list, description="Individual trade records")
    
    # Benchmark comparison
    benchmark_return: Optional[float] = Field(None, description="Benchmark total return %")
    alpha: Optional[float] = Field(None, description="Alpha vs benchmark")
    information_ratio: Optional[float] = Field(None, description="Information ratio")
    
    @validator("win_rate", pre=True, always=True)
    def calculate_win_rate(cls, v, values):
        """Calculate win rate from trade counts."""
        if v is None:
            total = values.get("total_trades", 0)
            winning = values.get("winning_trades", 0)
            return (winning / total * 100) if total > 0 else 0
        return v


class MLModelMetrics(BaseModel):
    """Machine learning model performance metrics."""
    model_id: str = Field(..., description="Unique model identifier")
    model_name: str = Field(..., description="Model name")
    model_version: str = Field(..., description="Model version")
    model_type: str = Field(..., description="Model type (e.g., lightgbm, lstm)")
    
    # Training metadata
    training_start: datetime = Field(..., description="Training start time")
    training_end: datetime = Field(..., description="Training end time")
    training_samples: int = Field(..., description="Number of training samples")
    validation_samples: int = Field(..., description="Number of validation samples")
    
    # Model performance metrics
    accuracy: Optional[float] = Field(None, description="Classification accuracy")
    precision: Optional[float] = Field(None, description="Precision score")
    recall: Optional[float] = Field(None, description="Recall score")
    f1_score: Optional[float] = Field(None, description="F1 score")
    auc_roc: Optional[float] = Field(None, description="AUC-ROC score")
    
    # Regression metrics (if applicable)
    mse: Optional[float] = Field(None, description="Mean squared error")
    mae: Optional[float] = Field(None, description="Mean absolute error")
    r2_score: Optional[float] = Field(None, description="R-squared score")
    
    # Trading-specific metrics
    hit_rate: Optional[float] = Field(None, description="Signal hit rate %")
    information_coefficient: Optional[float] = Field(None, description="Information coefficient")
    sharpe_ratio: Optional[float] = Field(None, description="Strategy Sharpe ratio")
    
    # Feature importance
    feature_importance: Dict[str, float] = Field(
        default_factory=dict,
        description="Feature importance scores"
    )
    
    # Model artifacts
    model_path: str = Field(..., description="Path to saved model")
    feature_names: List[str] = Field(default_factory=list, description="Feature names")
    hyperparameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Model hyperparameters"
    )
    
    # Deployment status
    is_production: bool = Field(default=False, description="Is model in production")
    deployment_date: Optional[datetime] = Field(None, description="Production deployment date")


class RiskMetrics(BaseModel):
    """Risk metrics for portfolio or position."""
    entity_id: str = Field(..., description="Portfolio or position ID")
    entity_type: str = Field(..., description="'portfolio' or 'position'")
    timestamp: datetime = Field(..., description="Calculation timestamp")
    
    # Value at Risk
    var_95_1d: Decimal = Field(..., description="1-day VaR 95%")
    var_99_1d: Decimal = Field(..., description="1-day VaR 99%")
    cvar_95_1d: Decimal = Field(..., description="1-day CVaR 95%")
    
    # Volatility metrics
    realized_volatility_1d: float = Field(..., description="1-day realized volatility")
    realized_volatility_30d: float = Field(..., description="30-day realized volatility")
    implied_volatility: Optional[float] = Field(None, description="Implied volatility if available")
    
    # Greek exposures (for options)
    delta: Optional[float] = Field(None, description="Delta exposure")
    gamma: Optional[float] = Field(None, description="Gamma exposure")
    theta: Optional[float] = Field(None, description="Theta exposure")
    vega: Optional[float] = Field(None, description="Vega exposure")
    rho: Optional[float] = Field(None, description="Rho exposure")
    
    # Risk factors
    market_beta: float = Field(..., description="Market beta")
    sector_exposures: Dict[str, float] = Field(
        default_factory=dict,
        description="Sector exposure breakdown"
    )
    country_exposures: Dict[str, float] = Field(
        default_factory=dict,
        description="Country exposure breakdown"
    )
    
    # Stress test results
    stress_test_scenarios: Dict[str, float] = Field(
        default_factory=dict,
        description="Stress test scenario results"
    )


class PerformanceAttribution(BaseModel):
    """Performance attribution analysis."""
    attribution_id: str = Field(..., description="Attribution analysis ID")
    portfolio_id: str = Field(..., description="Portfolio ID")
    period_start: datetime = Field(..., description="Analysis period start")
    period_end: datetime = Field(..., description="Analysis period end")
    
    # Total return breakdown
    total_return: float = Field(..., description="Total portfolio return %")
    
    # Attribution by strategy
    strategy_attribution: Dict[str, Dict[str, float]] = Field(
        default_factory=dict,
        description="Attribution by strategy (return, weight, contribution)"
    )
    
    # Attribution by asset class
    asset_class_attribution: Dict[str, Dict[str, float]] = Field(
        default_factory=dict,
        description="Attribution by asset class"
    )
    
    # Attribution by security
    security_attribution: Dict[str, Dict[str, float]] = Field(
        default_factory=dict,
        description="Attribution by individual security"
    )
    
    # Factor exposures
    factor_returns: Dict[str, float] = Field(
        default_factory=dict,
        description="Factor returns during period"
    )
    factor_exposures: Dict[str, float] = Field(
        default_factory=dict,
        description="Average factor exposures"
    )
    factor_contributions: Dict[str, float] = Field(
        default_factory=dict,
        description="Factor contributions to return"
    )


# Request/Response models for API endpoints
class SignalRequest(BaseModel):
    """Request to generate signals for symbols."""
    symbols: List[str] = Field(..., description="List of symbols")
    strategy_ids: Optional[List[str]] = Field(None, description="Specific strategies to run")
    timeframe: Optional[str] = Field("1m", description="Data timeframe")
    lookback_periods: Optional[int] = Field(100, description="Historical periods to analyze")


class BacktestRequest(BaseModel):
    """Request to run backtest."""
    strategy_name: str = Field(..., description="Strategy to backtest")
    symbols: List[str] = Field(..., description="Symbols to include")
    start_date: str = Field(..., description="Start date (YYYY-MM-DD)")
    end_date: str = Field(..., description="End date (YYYY-MM-DD)")
    initial_capital: float = Field(default=1000000.0, description="Initial capital")
    commission_rate: Optional[float] = Field(None, description="Commission rate override")
    benchmark: Optional[str] = Field("SPY", description="Benchmark symbol")
    
    # Advanced parameters
    rebalance_frequency: Optional[str] = Field("daily", description="Rebalancing frequency")
    risk_model: Optional[str] = Field(None, description="Risk model override")
    custom_params: Optional[Dict[str, Any]] = Field(None, description="Custom strategy parameters")


class PortfolioSummaryResponse(BaseModel):
    """Portfolio summary response."""
    portfolio_id: str
    timestamp: datetime
    total_value: float
    daily_pnl: float
    total_return: float
    position_count: int
    leverage: float
    max_drawdown: float
    sharpe_ratio: Optional[float]
    top_positions: List[Dict[str, Any]]
    risk_metrics: Dict[str, float]


class HealthCheckResponse(BaseModel):
    """Strategy engine health check response."""
    status: str = Field(..., description="Service status")
    timestamp: datetime = Field(..., description="Check timestamp")
    version: str = Field(..., description="Service version")
    uptime_seconds: float = Field(..., description="Service uptime")
    active_strategies: int = Field(..., description="Number of active strategies")
    total_positions: int = Field(..., description="Total open positions")
    portfolio_value: float = Field(..., description="Total portfolio value")
    last_signal_time: Optional[datetime] = Field(None, description="Last signal generation")


# Union types for polymorphic handling
MarketData = Union[Dict[str, Any]]  # Will be defined by data-ingest schemas
StrategyEvent = Union[Signal, Order, Position]